Repository etcd-io/bbolt, pull requests merged in 2023-08, with the labels that each got.

#540 Documentation: added a doc for bbolt command-line.
  cmd/bbolt/README.md
Labels: area/bbolt-cli, stage/merge-when-test-green, area/documentation

#548 Updated go to latest patch release 1.19.12
  .github/workflows/failpoint_test.yaml
  .github/workflows/tests.yaml
Labels: stage/merge-when-test-green

#550 bucket: allow to allocate key on stack in Put()
  bucket.go
Labels: area/performance

#554 fix Continuing typo
  cmd/bbolt/page_command.go
Labels: stage/merge-when-test-green

#555 Update to golang 1.20 minor release
  .github/workflows/failpoint_test.yaml
  .github/workflows/tests.yaml
  cmd/bbolt/main_test.go
  freelist_test.go
  go.mod
  manydbs_test.go
  simulation_test.go
Labels: type/cleanup

#556 delete unnecessary error info
  errors.go
  errors/errors.go
Labels: type/cleanup
