Repository etcd-io/bbolt, pull requests merged in 2024-06, with the labels that each got.

#767 cmd/bbolt: write bench results to stdout
  cmd/bbolt/main.go
  cmd/bbolt/main_test.go
Labels: size/S

#771 Dependency Bump: gofail to v0.2.0
  go.mod
  go.sum
Labels: size/XS

#772 Add verification on mergeSpans
  freelist.go
  freelist_hmap.go
Labels: size/L

#774 change FileMode var formatter to %s
  db.go
Labels: stage/merge-when-test-green, size/XS

#776 Explicitly set the pagesize as 4096 for the concurrent test
  concurrent_test.go
Labels: size/XS

#777 move array related freelist functions into own file
  freelist.go
  freelist_array.go
Labels: stage/merge-when-test-green, size/L

#750 Add PR benchmarking
  .github/workflows/benchmark-pr.yaml
  Makefile
  scripts/compare_benchmarks.sh
Labels: size/L
