Repository etcd-io/bbolt, pull requests merged in 2024-07, with the labels that each got.

#779 Enhance `TestDB_Concurrent_WriteTo` to check consistent read
  db_test.go
Labels: size/L

#784 Bump Go version to 1.22.5: GO-2024-2963 fix
  .go-version
  go.mod
Labels: stage/merge-when-test-green, size/XS

#785 [1.3] Bump Go version to 1.21.12: GO-2024-2963 fix
  .go-version
Labels: stage/merge-when-test-green, size/XS

#775 introduce a freelist interface
  allocate_test.go
  bucket.go
  bucket_test.go
  cmd/bbolt/command_version.go
  db.go
  freelist.go
  freelist_test.go
  internal/freelist/array.go
  internal/freelist/array_test.go
  internal/freelist/freelist.go
  internal/freelist/freelist_test.go
  internal/freelist/hashmap.go
  internal/freelist/hashmap_test.go
  internal/freelist/shared.go
  node.go
  tx.go
  tx_check.go
Labels: size/XXL, approved, lgtm

#788 No need to handle freelist as a specical case when freeing a page
  internal/freelist/shared.go
Labels: size/XS, approved, lgtm

#794 ensure hashmap init clears maps
  internal/freelist/array.go
  internal/freelist/freelist_test.go
  internal/freelist/hashmap.go
  internal/freelist/shared.go
Labels: size/L, approved

#792 Panicking when a write txn tries to free a page which was allocated by itself
  internal/freelist/shared.go
Labels: size/S, approved, lgtm

#801 github/workflows: pin dependency versions
  .github/workflows/failpoint_test.yaml
  .github/workflows/robustness_template.yaml
  .github/workflows/stale.yaml
  .github/workflows/tests-template.yml
  .github/workflows/tests_amd64.yaml
  .github/workflows/tests_windows.yml
Labels: size/S, approved
