Repository etcd-io/bbolt, pull requests merged in 2024-08, with the labels that each got.

#803 github/workflows: set top-level file permissions
  .github/workflows/gh-workflow-approve.yaml
  .github/workflows/tests_windows.yml
Labels: stage/merge-when-test-green, size/XS, approved

#805 [1.3] cmd/bbolt: write bench results to stdout
  cmd/bbolt/main.go
Labels: size/XS

#804 Dedupe Reload/NoSyncReload, prefer empty instead of nil init
  internal/freelist/freelist.go
  internal/freelist/shared.go
Labels: stage/merge-when-test-green, size/M

#811 Update GitHub runners to use ubuntu-latest since they have nested virt
  .github/workflows/benchmark-template.yaml
  .github/workflows/robustness_nightly.yaml
  .github/workflows/robustness_test.yaml
  .github/workflows/tests_amd64.yaml
Labels: ok-to-test, size/S, approved

#812 [1.3] backport go-dmflakey and robustness test
  .github/workflows/robustness_test.yaml
  Makefile
  tests/dmflakey/dmflakey.go
  tests/dmflakey/dmflakey_test.go
  tests/dmflakey/dmsetup.go
  tests/dmflakey/loopback.go
  tests/robustness/main_test.go
  tests/robustness/powerfailure_test.go
  tests/utils/helpers.go
  tx.go
Labels: lgtm, size/XL

#813 [release-1.3] go version bump from 1.21.12 to 1.21.13
  .go-version
  go.mod
Labels: size/XS

#814 go version bump from 1.22.5 to 1.22.6
  .go-version
  go.mod
Labels: size/XS, approved

#816 [1.3] backport failpoints(resizeFileError, lackOfDiskSpace) and dmflakey on XFS
  .github/workflows/robustness_test.yaml
  db.go
  tests/dmflakey/dmflakey.go
  tests/dmflakey/dmflakey_test.go
  tests/failpoint/db_failpoint_test.go
  tests/robustness/powerfailure_test.go
  tx.go
Labels: size/L, lgtm

#817 [1.3] tests/robustness: switch to kill if no panic after 10sec
  tests/robustness/powerfailure_test.go
Labels: size/XS, lgtm

#821 [main] Bump go toolchain to 1.23.0
  .github/workflows/tests-template.yml
  .github/workflows/tests_windows.yml
  .go-version
  db.go
  go.mod
Labels: size/S, approved

#822 [release-1.3] Bump go toolchain to 1.22.6
  .github/workflows/tests.yaml
  .go-version
  db.go
  go.mod
Labels: size/S

#819 Rollback alloc map: remove all page ids which are allocated by the txid
  internal/freelist/array_test.go
  internal/freelist/hashmap_test.go
  internal/freelist/shared.go
Labels: size/M, approved, lgtm

#823 [1.3] Rollback alloc map: remove all page ids which are allocated by the txid
  freelist.go
  freelist_test.go
Labels: size/M, lgtm

#824 Add changelog for 1.3.11
  CHANGELOG/CHANGELOG-1.3.md
Labels: size/S, approved, lgtm

#786 add freelist interface unit tests
  internal/freelist/array_test.go
  internal/freelist/freelist_test.go
  internal/freelist/hashmap_test.go
Labels: size/L, approved

#826 Update release date of 1.3.11
  CHANGELOG/CHANGELOG-1.3.md
Labels: size/XS, approved, lgtm

#828 Add info on how to iterate over existing buckets
  README.md
Labels: ok-to-test, size/S, approved
