Repository etcd-io/bbolt, pull requests merged in 2024-11, with the labels that each got.

#847 Add changelog for 1.4.0-beta.0
  CHANGELOG/CHANGELOG-1.4.md
Labels: size/S, approved

#852 Update release date for v1.4.0-beta.0
  CHANGELOG/CHANGELOG-1.4.md
Labels: size/XS, approved

#855 chore/docs: Installing document description should use bbolt
  README.md
Labels: ok-to-test, size/XS, approved

#856 Bump go toolchain to 1.23.3
  .go-version
  go.mod
Labels: ok-to-test, size/XS, approved

#862 [1.3] update go version to 1.22.9
  .go-version
  go.mod
Labels: ok-to-test, size/XS
