Repository etcd-io/bbolt, pull requests merged in 2024-10, with the labels that each got.

#836 Bump go version to 1.23.2
  .github/workflows/tests-template.yml
  .github/workflows/tests_windows.yml
  .go-version
  go.mod
Labels: size/XS, approved

#837 [1.3] Bump go version to 1.22.8
  .github/workflows/tests.yaml
  .go-version
  go.mod
Labels: size/XS

#841 github: enable ok-to-test for release-1.3 PRs
  .github/workflows/gh-workflow-approve.yaml
Labels: size/XS, approved

#844 github/workflows: remove arm64 jobs
  .github/workflows/robustness_nightly.yaml
  .github/workflows/robustness_test.yaml
  .github/workflows/tests_arm64.yaml
  Makefile
Labels: size/M, approved
