Repository etcd-io/bbolt, pull requests merged in 2024-05, with the labels that each got.

#743 Update readme to clearly clarify the behaviour of Next and Prev
  README.md
Labels: backport/v1.3

#754 [1.3] dependency : update the go version to 1.21.10
  .go-version
Labels: stage/merge-when-test-green

#753 dependency : update go version to 1.22.3
  .go-version
  go.mod
Labels: stage/merge-when-test-green, ok-to-test
