Repository etcd-io/bbolt, pull requests merged in 2025-02, with the labels that each got.

#890 [1.4] Remove changelog from release-1.4
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
Labels: size/L, approved

#891 update golang toolchain to 1.23.6
  .go-version
  go.mod
Labels: ok-to-test, size/XS, approved

#892 [1.3] update golang toolchain to 1.22.12
  .go-version
  go.mod
Labels: ok-to-test, size/XS

#894 Update changelog for v1.4.0
  CHANGELOG/CHANGELOG-1.4.md
Labels: size/XS, approved

#904 Fix debug sync log line
  db.go
Labels: size/XS, approved

#906 Add code of conduct
  code-of-conduct.md
Labels: size/XS, approved

#909 Bump go linter 1.24
  .github/workflows/tests-template.yml
  .github/workflows/tests_windows.yml
Labels: size/XS, approved

#915 bump golangci-lint v1.64.5
  .github/workflows/tests-template.yml
Labels: size/XS, approved

#916 bump golangci-lint v1.64.5-win
  .github/workflows/tests_windows.yml
Labels: size/XS, approved
