Repository etcd-io/bbolt, pull requests merged in 2025-06, with the labels that each got.

#903 release: add release script
  scripts/release.sh
Labels: size/M, approved

#966 chore: use %w to wrap returned err by unix funcs
  db.go
Labels: ok-to-test, size/XS, approved

#968 Fix panicking being caused by huge object size
  bolt_386.go
  bolt_amd64.go
  bolt_arm.go
  bolt_arm64.go
  bolt_loong64.go
  bolt_mips64x.go
  bolt_mipsx.go
  bolt_ppc.go
  bolt_ppc64.go
  bolt_ppc64le.go
  bolt_riscv64.go
  bolt_s390x.go
  bolt_unix.go
  bolt_windows.go
  db.go
  db_test.go
  internal/common/bolt_386.go
  internal/common/bolt_amd64.go
  internal/common/bolt_arm.go
  internal/common/bolt_arm64.go
  internal/common/bolt_loong64.go
  internal/common/bolt_mips64x.go
  internal/common/bolt_mipsx.go
  internal/common/bolt_ppc.go
  internal/common/bolt_ppc64.go
  internal/common/bolt_ppc64le.go
  internal/common/bolt_riscv64.go
  internal/common/bolt_s390x.go
  internal/common/types.go
  internal/common/unsafe.go
  tx.go
Labels: size/L, approved, backport/v1.4

#974 [release-1.4] Revert "Merge pull request #969 from nspcc-dev/drop-unused-txs"
  db.go
Labels: size/S, approved

#983 Bump Go to 1.24.4
  .go-version
  go.mod
Labels: ok-to-test, size/XS, approved

#984 [release-1.3] Bump Go to 1.23.10
  .go-version
  go.mod
Labels: ok-to-test, size/XS

#977 Make statistics optional
  db.go
  tx.go
Labels: ok-to-test, size/M, approved

#990 [release-1.4] Fix maxMapSize typo in aix, android and solaris
  bolt_aix.go
  bolt_android.go
  bolt_solaris.go
Labels: size/S, approved

#991 Update changelog for 1.4.2 and 1.5.0
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
Labels: size/S, approved

#993 chore(CI): add goimports to linter
  .github/workflows/failpoint_test.yaml
  .github/workflows/robustness_template.yaml
  .github/workflows/tests-template.yml
  .github/workflows/tests_amd64.yaml
  .github/workflows/tests_arm64.yaml
  .github/workflows/tests_windows.yml
  .golangci.yaml
  bolt_aix.go
  bolt_android.go
  bolt_solaris.go
  cmd/bbolt/main_test.go
  movebucket_test.go
  tests/dmflakey/dmflakey_test.go
  tests/robustness/powerfailure_test.go
Labels: size/M, approved

#986 chore(CI): Add QEMU based CI Workflow
  .github/workflows/cross-arch-test.yaml
Labels: size/L, approved

#989 tx: add missing lock on meta page update
  tx.go
Labels: backport/v1.3, ok-to-test, size/XS, approved, backport/v1.4

#999 Add template to cross arch build tests
  .github/workflows/cross-arch-template.yaml
  .github/workflows/cross-arch-test.yaml
Labels: size/L, approved

#980 release: Switch branch to stable branch from script
  scripts/release.sh
Labels: size/L, approved

#1005 [release-1.4] Protect meta page when it's being written
  tx.go
Labels: size/XS, approved

#1006 [release-1.3] Protect meta page when it's being written
  tx.go
Labels: size/XS

#1008 Update v1.4.2's release date
  CHANGELOG/CHANGELOG-1.4.md
Labels: size/XS, approved

#1009 chore(release): fix release script for MacOS
  scripts/release.sh
Labels: size/XS, approved
