Repository etcd-io/bbolt, pull requests merged in 2025-04, with the labels that each got.

#938 [release-1.4] Bump go to 1.23.8
  .go-version
  go.mod
Labels: ok-to-test, size/XS

#937 [release-1.3] Bump go to 1.23.8
  .go-version
  go.mod
Labels: ok-to-test, size/XS

#942 Clarify the effect of InitialMmapSize on Windows platform
  db.go
Labels: size/XS, approved

#943 [release-1.4] Clarify the effect of InitialMmapSize on Windows platform
  db.go
Labels: size/XS, approved

#944 [release-1.3] Clarify the effect of InitialMmapSize on Windows platform
  db.go
Labels: size/XS

#948 test: deflaky dmflakey.Teardown issue
  .github/workflows/robustness_template.yaml
  tests/dmflakey/dmflakey.go
Labels: size/M, approved

#929 add support for data file size limit
  bolt_windows.go
  db.go
  db_test.go
  errors/errors.go
  internal/btesting/btesting.go
Labels: ok-to-test, size/L, approved
