Repository etcd-io/bbolt, pull requests merged in 2025-05, with the labels that each got.

#955 Bump Go to 1.24.3
  .go-version
  go.mod
Labels: size/XS, approved

#954 chore: bump golangci-lint to v2.1.6
  .github/workflows/tests-template.yml
  .github/workflows/tests_windows.yml
  .golangci.yaml
Labels: size/M, approved

#963 fix staticcheck issues
  .golangci.yaml
  cmd/bbolt/main.go
  internal/common/page.go
  tests/robustness/powerfailure_test.go
  tx_check.go
Labels: size/S, approved
