Repository etcd-io/bbolt, pull requests merged in 2025-07, with the labels that each got.

#1013 chore(cmd): migrate `info` command to cobra style
  cmd/bbolt/command_info.go
  cmd/bbolt/command_info_test.go
  cmd/bbolt/command_root.go
  cmd/bbolt/main.go
  cmd/bbolt/main_test.go
Labels: size/L, approved

#1012 cmd: migrate `compact` command to cobra style
  cmd/bbolt/command_compact.go
  cmd/bbolt/command_compact_test.go
  cmd/bbolt/command_root.go
  cmd/bbolt/main.go
  cmd/bbolt/main_test.go
Labels: ok-to-test, size/L, approved

#1015 chore(cmd): migrate `pages` command to cobra style
  cmd/bbolt/command_pages.go
  cmd/bbolt/command_pages_test.go
  cmd/bbolt/command_root.go
  cmd/bbolt/main.go
  cmd/bbolt/main_test.go
Labels: size/L, approved

#1016 chore(cmd): migrate `keys` command to cobra style
  cmd/bbolt/command_keys.go
  cmd/bbolt/command_keys_test.go
  cmd/bbolt/command_root.go
  cmd/bbolt/main.go
  cmd/bbolt/main_test.go
Labels: size/L, approved

#1019 cmd: migrate `page-item` command to cobra style
  cmd/bbolt/command_page_item.go
  cmd/bbolt/command_page_item_test.go
  cmd/bbolt/command_root.go
  cmd/bbolt/main.go
  cmd/bbolt/main_test.go
Labels: ok-to-test, size/L, approved

#1025 [release-1.3] Bump Go to 1.23.11
  .go-version
  go.mod
Labels: ok-to-test, size/XS

#987 add write mode "seq-del"
  cmd/bbolt/main.go
Labels: ok-to-test, size/M, approved

#1029 cmd: migrate `page` command to cobra style
  cmd/bbolt/command_page.go
  cmd/bbolt/command_page_test.go
  cmd/bbolt/command_root.go
  cmd/bbolt/main.go
  cmd/bbolt/main_test.go
  cmd/bbolt/page_command.go
Labels: ok-to-test, approved, size/XL

#1031 chore(test): bump_windows_test_timeout
  .github/workflows/tests_windows.yml
Labels: size/XS, approved

#1032 chore(test): bump_windows_test_timeout
  .github/workflows/tests_windows.yml
Labels: size/XS, approved

#1030 chore(cmd): add exclusive behaviour to page cmd
  cmd/bbolt/command_page.go
  cmd/bbolt/command_page_test.go
  cmd/bbolt/main.go
Labels: size/M, approved
