Repository etcd-io/bbolt, pull requests merged in 2025-08, with the labels that each got.

#1045 Fix test case TestDB_HugeValue for 32 bit systems
  db_test.go
Labels: size/S, approved, backport/v1.4

#1047 Bump Go to 1.24.6
  .go-version
  go.mod
Labels: size/XS, approved

#1057 Update (*Tx)WriteTo to reuse the already opened file if WriteFlag not set
  db_test.go
  tx.go
Labels: size/L, approved

#1059 [release-1.3] Update (*Tx)WriteTo to reuse the already opened file if WriteFlag not set
  db_test.go
  tx.go
Labels: size/L

#1064 Update release date for 1.3.12 and 1.4.3
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
Labels: size/XS, approved

#1065 fix a typo
  tx.go
Labels: ok-to-test, size/XS, approved

#1066 [release-1.4] fix a typo
  tx.go
Labels: size/XS, approved

#1070 [release-1.4]: Bump Go to 1.24.6
  .go-version
  go.mod
Labels: ok-to-test, size/XS
