Repository etcd-io/bbolt, pull requests merged in 2025-03, with the labels that each got.

#913 chore: setup golangci-lint config file
  .gitattributes
  .golangci.yaml
Labels: size/S, approved

#921 [1.4] Bump go toolchain to v1.23.7
  .go-version
  go.mod
Labels: ok-to-test, size/XS

#920 [1.3] Bump go toolchain to v1.23.7
  .go-version
  go.mod
Labels: ok-to-test, size/XS

#924 [2025-03-10] Manual dependency update
  go.mod
  go.sum
Labels: size/S, approved

#907 Bump go 1.24.0
  .go-version
  go.mod
Labels: stage/merge-when-test-green, size/XS, approved

#925 Bump go 1.24.1
  .go-version
  go.mod
Labels: size/XS, approved

#926 Use GitHub runners for arm64 robustness tests
  .github/workflows/robustness_test.yaml
  .github/workflows/tests-template.yml
  .github/workflows/tests_arm64.yaml
Labels: size/M, approved
